// These classes are not used by the MobileNet model, but are kept for reference
// in case a different flower-specific model is used in the future.
export const FLOWER_CLASSES: { [classIndex: number]: string } = {
  0: 'pink primrose',
  1: 'hard-leaved pocket orchid',
  2: 'canterbury bells',
  3: 'sweet pea',
  4: 'english marigold',
  5: 'tiger lily',
  6: 'moon orchid',
  7: 'parasol',
  8: 'blanket flower',
  9: 'trumpet creeper',
  10: 'blackberry lily',
  11: 'common dandelion',
  12: 'king protea',
  13: 'love in the mist',
  14: 'monkshood',
  15: 'globe thistle',
  16: 'globe-flower',
  17: 'grape hyacinth',
  18: 'corn poppy',
  19: 'prince of wales feathers',
  20: 'stemless gentian',
  21: 'artichoke',
  22: 'sweet william',
  23: 'carnation',
  24: 'garden phlox',
  25: 'peruvian lily',
  26: 'common tulip',
  27: 'pincushion flower',
  28: 'foxglove',
  29: 'clematis',
  30: 'frangipani',
  31: 'fritillary',
  32: 'great masterwort',
  33: 'giant white arum lily',
  34: 'fire lily',
  35: 'toad lily',
  36: 'siam tulip',
  37: 'gazania',
  38: 'bold eagle',
  39: 'sunflower',
  40: 'geranium',
  41: 'snapdragon',
  42: 'columbine',
  43: 'desert-rose',
  44: 'tree mallow',
  45: 'magnolia',
  46: 'cyclamen',
  47: 'watercress',
  48: 'canna lily',
  49: 'hippeastrum',
  50: 'bee balm',
  51: 'ball moss',
  52: 'passion flower',
  53: 'petunia',
  54: 'wild pansy',
  55: 'primula',
  56: 'turning lily',
  57: 'tree poppy',
  58: 'mexican aster',
  59: 'japanese anemone',
  60: 'black-eyed susan',
  61: 'silverbush',
  62: 'californian poppy',
  63: 'osteospermum',
  64: 'spring crocus',
  65: 'bearded iris',
  66: 'windflower',
  67: 'tree of heaven',
  68: 'azalea',
  69: 'thorn apple',
  70: 'golden celebration',
  71: 'poinsettia',
  72: 'primrose',
  73: 'morning glory',
  74: 'spear thistle',
  75: 'yellow iris',
  76: 'cautleya spicata',
  77: 'lenten rose',
  78: 'marigold',
  79: 'common star of bethlehem',
  80: 'bougainvillea',
  81: 'water lily',
  82: 'hibiscus',
  83: 'purple coneflower',
  84: 'perennial',
  85: 'common chokecherry',
  86: 'anthurium',
  87: 'cherokee rose',
  88: 'st. bernard lily',
  89: 'lotus',
  90: 'barbeton daisy',
  91: 'daffodil',
  92: 'sword lily',
  93: 'oxeye daisy',
  94: 'common peony',
  95: 'alpine sea holly',
  96: 'ruby-lipped cattleya',
  97: 'cape flower',
  98: 'giant white arum lily',
  99: 'great masterwort',
  100: 'tree mallow',
  101: 'magnolia',
};
